// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function FetchDatabaseData(arg1) {
  return window['go']['main']['App']['FetchDatabaseData'](arg1);
}

export function GetConnectionPassword(arg1) {
  return window['go']['main']['App']['GetConnectionPassword'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}
