// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function FetchDatabaseData(arg1) {
  return window['go']['main']['App']['FetchDatabaseData'](arg1);
}

export function FetchDatabaseDataStreaming(arg1) {
  return window['go']['main']['App']['FetchDatabaseDataStreaming'](arg1);
}

export function GetConnectionPassword(arg1) {
  return window['go']['main']['App']['GetConnectionPassword'](arg1);
}

export function GetRuntimeInfo() {
  return window['go']['main']['App']['GetRuntimeInfo']();
}

export function GetThemeCSS(arg1) {
  return window['go']['main']['App']['GetThemeCSS'](arg1);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function RestartEngine() {
  return window['go']['main']['App']['RestartEngine']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
