// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function FetchDatabaseData(arg1:string):Promise<string>;

export function FetchDatabaseDataStreaming(arg1:string):Promise<string>;

export function GetConnectionPassword(arg1:string):Promise<string>;

export function IsDevMode():Promise<boolean>;

export function ListConnections():Promise<Array<main.SavedConnection>>;

export function SaveConnection(arg1:main.SaveConnectionInput):Promise<main.SavedConnection>;
